import { ItemData } from '../data/ItemDataLoader'

/**
 * Mock item data for testing ItemSpawnService
 * Provides minimal but complete item templates for all categories
 */
export const mockItemData: ItemData = {
  potions: [
    { type: 'HEAL', effect: 'restore_hp', power: '1d8', rarity: 'common', descriptors: ['red', 'crimson', 'ruby'] },
    { type: 'EXTRA_HEAL', effect: 'restore_hp', power: '3d8', rarity: 'uncommon', descriptors: ['pink', 'rose', 'magenta'] },
    { type: 'GAIN_STRENGTH', effect: 'increase_strength', power: '1', rarity: 'uncommon', descriptors: ['blue', 'azure', 'sapphire'] },
    { type: 'RESTORE_STRENGTH', effect: 'restore_strength', power: '1', rarity: 'common', descriptors: ['green', 'emerald', 'jade'] },
    { type: 'POISON', effect: 'damage', power: '1d6', rarity: 'common', descriptors: ['black', 'dark', 'ebony'] },
    { type: 'HASTE_SELF', effect: 'haste', power: '1d10', rarity: 'uncommon', descriptors: ['yellow', 'golden', 'amber'] },
    { type: 'RAISE_LEVEL', effect: 'level_up', power: '1', rarity: 'rare', descriptors: ['silver', 'platinum', 'white'] },
    { type: 'CONFUSION', effect: 'confuse', power: '1d10', rarity: 'common', descriptors: ['orange', 'tangerine', 'bronze'] },
    { type: 'BLINDNESS', effect: 'blind', power: '1d10', rarity: 'common', descriptors: ['purple', 'violet', 'amethyst'] },
    { type: 'DETECT_MONSTERS', effect: 'detect_monsters', power: '0', rarity: 'uncommon', descriptors: ['brown', 'tan', 'beige'] },
    { type: 'DETECT_MAGIC', effect: 'detect_magic', power: '0', rarity: 'uncommon', descriptors: ['grey', 'silver', 'smoky'] },
    { type: 'SEE_INVISIBLE', effect: 'see_invisible', power: '1d10', rarity: 'uncommon', descriptors: ['clear', 'transparent', 'glassy'] },
    { type: 'LEVITATION', effect: 'levitate', power: '1d10', rarity: 'uncommon', descriptors: ['cyan', 'turquoise', 'aqua'] },
  ],
  scrolls: [
    { type: 'IDENTIFY', effect: 'identify_item', rarity: 'common', labels: ['LABEL_A', 'LABEL_B', 'LABEL_C'] },
    { type: 'ENCHANT_WEAPON', effect: 'enchant_weapon', rarity: 'uncommon', labels: ['LABEL_D', 'LABEL_E', 'LABEL_F'] },
    { type: 'ENCHANT_ARMOR', effect: 'enchant_armor', rarity: 'uncommon', labels: ['LABEL_G', 'LABEL_H', 'LABEL_I'] },
    { type: 'MAGIC_MAPPING', effect: 'reveal_map', rarity: 'uncommon', labels: ['LABEL_J', 'LABEL_K', 'LABEL_L'] },
    { type: 'TELEPORTATION', effect: 'teleport', rarity: 'common', labels: ['LABEL_M', 'LABEL_N', 'LABEL_O'] },
    { type: 'REMOVE_CURSE', effect: 'remove_curse', rarity: 'uncommon', labels: ['LABEL_P', 'LABEL_Q', 'LABEL_R'] },
    { type: 'CREATE_MONSTER', effect: 'create_monster', rarity: 'uncommon', labels: ['LABEL_S', 'LABEL_T', 'LABEL_U'] },
    { type: 'SCARE_MONSTER', effect: 'scare', rarity: 'rare', labels: ['LABEL_V', 'LABEL_W', 'LABEL_X'] },
    { type: 'LIGHT', effect: 'light_room', rarity: 'common', labels: ['LABEL_Y', 'LABEL_Z', 'LABEL_AA'] },
    { type: 'SLEEP', effect: 'sleep', rarity: 'uncommon', labels: ['LABEL_AB', 'LABEL_AC', 'LABEL_AD'] },
    { type: 'HOLD_MONSTER', effect: 'hold', rarity: 'rare', labels: ['LABEL_AE', 'LABEL_AF', 'LABEL_AG'] },
  ],
  rings: [
    { type: 'PROTECTION', effect: 'ac_bonus', power: '1d3', hungerModifier: 0, rarity: 'uncommon', materials: ['gold', 'silver', 'bronze'] },
    { type: 'REGENERATION', effect: 'regen', power: '1', hungerModifier: 2, rarity: 'uncommon', materials: ['ruby', 'diamond', 'sapphire'] },
    { type: 'SEARCHING', effect: 'search_bonus', power: '1d3', hungerModifier: 0, rarity: 'uncommon', materials: ['iron', 'steel', 'platinum'] },
    { type: 'SEE_INVISIBLE', effect: 'see_invisible', power: '1', hungerModifier: 0, rarity: 'rare', materials: ['glass', 'crystal', 'quartz'] },
    { type: 'SLOW_DIGESTION', effect: 'slow_hunger', power: '1', hungerModifier: -1, rarity: 'uncommon', materials: ['copper', 'brass', 'tin'] },
    { type: 'ADD_STRENGTH', effect: 'strength_bonus', power: '1d3', hungerModifier: 1, rarity: 'uncommon', materials: ['jade', 'emerald', 'topaz'] },
    { type: 'SUSTAIN_STRENGTH', effect: 'sustain_strength', power: '1', hungerModifier: 0, rarity: 'uncommon', materials: ['pearl', 'opal', 'onyx'] },
    { type: 'DEXTERITY', effect: 'dexterity_bonus', power: '1d3', hungerModifier: 0, rarity: 'uncommon', materials: ['obsidian', 'amber', 'coral'] },
    { type: 'TELEPORTATION', effect: 'teleport', power: '1', hungerModifier: 1, rarity: 'rare', materials: ['moonstone', 'turquoise', 'agate'] },
    { type: 'STEALTH', effect: 'stealth', power: '1', hungerModifier: 1, rarity: 'rare', materials: ['wood', 'bone', 'ivory'] },
  ],
  wands: [
    { type: 'LIGHTNING', damage: '6d6', charges: '3d3', rarity: 'uncommon', woods: ['oak', 'ash', 'pine'] },
    { type: 'FIRE', damage: '6d6', charges: '3d3', rarity: 'uncommon', woods: ['maple', 'birch', 'cedar'] },
    { type: 'COLD', damage: '6d6', charges: '3d3', rarity: 'uncommon', woods: ['willow', 'elm', 'fir'] },
    { type: 'MAGIC_MISSILE', damage: '2d6', charges: '4d4', rarity: 'common', woods: ['cherry', 'walnut', 'mahogany'] },
    { type: 'SLEEP', damage: '0', charges: '3d3', rarity: 'uncommon', woods: ['yew', 'hazel', 'poplar'] },
    { type: 'HASTE_MONSTER', damage: '0', charges: '3d3', rarity: 'rare', woods: ['hickory', 'alder', 'beech'] },
    { type: 'SLOW_MONSTER', damage: '0', charges: '3d3', rarity: 'uncommon', woods: ['spruce', 'cypress', 'redwood'] },
    { type: 'POLYMORPH', damage: '0', charges: '3d3', rarity: 'rare', woods: ['ebony', 'rosewood', 'teak'] },
    { type: 'TELEPORT_AWAY', damage: '0', charges: '3d3', rarity: 'uncommon', woods: ['bamboo', 'balsa', 'sandalwood'] },
    { type: 'CANCELLATION', damage: '0', charges: '3d3', rarity: 'rare', woods: ['ironwood', 'boxwood', 'dogwood'] },
  ],
  weapons: [
    { name: 'Dagger', damage: '1d6', rarity: 'common' },
    { name: 'Short Sword', damage: '1d8', rarity: 'common' },
    { name: 'Mace', damage: '2d4', rarity: 'common' },
    { name: 'Spear', damage: '2d3', rarity: 'common' },
    { name: 'Long Sword', damage: '1d12', rarity: 'uncommon' },
    { name: 'Battle Axe', damage: '2d8', rarity: 'uncommon' },
    { name: 'Flail', damage: '2d5', rarity: 'uncommon' },
    { name: 'Two-Handed Sword', damage: '3d6', rarity: 'rare' },
  ],
  armor: [
    { name: 'Leather Armor', ac: 8, rarity: 'common' },
    { name: 'Studded Leather', ac: 7, rarity: 'common' },
    { name: 'Ring Mail', ac: 7, rarity: 'uncommon' },
    { name: 'Scale Mail', ac: 6, rarity: 'uncommon' },
    { name: 'Chain Mail', ac: 5, rarity: 'uncommon' },
    { name: 'Splint Mail', ac: 4, rarity: 'rare' },
    { name: 'Plate Mail', ac: 3, rarity: 'rare' },
  ],
  food: [{ name: 'Food Ration', nutrition: '900', rarity: 'common' }],
  lightSources: [
    { type: 'torch', name: 'Torch', radius: 2, fuel: 500, isPermanent: false, rarity: 'common' },
    {
      type: 'lantern',
      name: 'Lantern',
      radius: 2,
      fuel: 500,
      isPermanent: false,
      rarity: 'uncommon',
    },
    {
      type: 'artifact',
      name: 'Phial of Galadriel',
      radius: 3,
      isPermanent: true,
      rarity: 'legendary',
    },
  ],
  consumables: [{ name: 'Oil Flask', type: 'lantern_fuel', fuelAmount: 500, rarity: 'uncommon' }],
}
