import { ItemData } from '../data/ItemDataLoader'

/**
 * Mock item data for testing ItemSpawnService
 * Provides minimal but complete item templates for all categories
 */
export const mockItemData: ItemData = {
  potions: [
    { type: 'HEAL', effect: 'restore_hp', power: '1d8', rarity: 'common' },
    { type: 'EXTRA_HEAL', effect: 'restore_hp', power: '3d8', rarity: 'uncommon' },
    { type: 'GAIN_STRENGTH', effect: 'increase_strength', power: '1', rarity: 'uncommon' },
    { type: 'RESTORE_STRENGTH', effect: 'restore_strength', power: '1', rarity: 'common' },
    { type: 'POISON', effect: 'damage', power: '1d6', rarity: 'common' },
    { type: 'HASTE_SELF', effect: 'haste', power: '1d10', rarity: 'uncommon' },
    { type: 'RAISE_LEVEL', effect: 'level_up', power: '1', rarity: 'rare' },
    { type: 'CONFUSION', effect: 'confuse', power: '1d10', rarity: 'common' },
    { type: 'BLINDNESS', effect: 'blind', power: '1d10', rarity: 'common' },
    { type: 'DETECT_MONSTERS', effect: 'detect_monsters', power: '0', rarity: 'uncommon' },
    { type: 'DETECT_MAGIC', effect: 'detect_magic', power: '0', rarity: 'uncommon' },
    { type: 'SEE_INVISIBLE', effect: 'see_invisible', power: '1d10', rarity: 'uncommon' },
    { type: 'LEVITATION', effect: 'levitate', power: '1d10', rarity: 'uncommon' },
  ],
  scrolls: [
    { type: 'IDENTIFY', effect: 'identify_item', rarity: 'common' },
    { type: 'ENCHANT_WEAPON', effect: 'enchant_weapon', rarity: 'uncommon' },
    { type: 'ENCHANT_ARMOR', effect: 'enchant_armor', rarity: 'uncommon' },
    { type: 'MAGIC_MAPPING', effect: 'reveal_map', rarity: 'uncommon' },
    { type: 'TELEPORTATION', effect: 'teleport', rarity: 'common' },
    { type: 'REMOVE_CURSE', effect: 'remove_curse', rarity: 'uncommon' },
    { type: 'CREATE_MONSTER', effect: 'create_monster', rarity: 'uncommon' },
    { type: 'SCARE_MONSTER', effect: 'scare', rarity: 'rare' },
    { type: 'LIGHT', effect: 'light_room', rarity: 'common' },
    { type: 'SLEEP', effect: 'sleep', rarity: 'uncommon' },
    { type: 'HOLD_MONSTER', effect: 'hold', rarity: 'rare' },
  ],
  rings: [
    { type: 'PROTECTION', effect: 'ac_bonus', rarity: 'uncommon' },
    { type: 'REGENERATION', effect: 'regen', rarity: 'uncommon' },
    { type: 'SEARCHING', effect: 'search_bonus', rarity: 'uncommon' },
    { type: 'SEE_INVISIBLE', effect: 'see_invisible', rarity: 'rare' },
    { type: 'SLOW_DIGESTION', effect: 'slow_hunger', rarity: 'uncommon' },
    { type: 'ADD_STRENGTH', effect: 'strength_bonus', rarity: 'uncommon' },
    { type: 'SUSTAIN_STRENGTH', effect: 'sustain_strength', rarity: 'uncommon' },
    { type: 'DEXTERITY', effect: 'dexterity_bonus', rarity: 'uncommon' },
    { type: 'TELEPORTATION', effect: 'teleport', rarity: 'rare' },
    { type: 'STEALTH', effect: 'stealth', rarity: 'rare' },
  ],
  wands: [
    { type: 'LIGHTNING', damage: '6d6', charges: '3d3', rarity: 'uncommon' },
    { type: 'FIRE', damage: '6d6', charges: '3d3', rarity: 'uncommon' },
    { type: 'COLD', damage: '6d6', charges: '3d3', rarity: 'uncommon' },
    { type: 'MAGIC_MISSILE', damage: '2d6', charges: '4d4', rarity: 'common' },
    { type: 'SLEEP', damage: '0', charges: '3d3', rarity: 'uncommon' },
    { type: 'HASTE_MONSTER', damage: '0', charges: '3d3', rarity: 'rare' },
    { type: 'SLOW_MONSTER', damage: '0', charges: '3d3', rarity: 'uncommon' },
    { type: 'POLYMORPH', damage: '0', charges: '3d3', rarity: 'rare' },
    { type: 'TELEPORT_AWAY', damage: '0', charges: '3d3', rarity: 'uncommon' },
    { type: 'CANCELLATION', damage: '0', charges: '3d3', rarity: 'rare' },
  ],
  weapons: [
    { name: 'Dagger', damage: '1d6', rarity: 'common' },
    { name: 'Short Sword', damage: '1d8', rarity: 'common' },
    { name: 'Mace', damage: '2d4', rarity: 'common' },
    { name: 'Spear', damage: '2d3', rarity: 'common' },
    { name: 'Long Sword', damage: '1d12', rarity: 'uncommon' },
    { name: 'Battle Axe', damage: '2d8', rarity: 'uncommon' },
    { name: 'Flail', damage: '2d5', rarity: 'uncommon' },
    { name: 'Two-Handed Sword', damage: '3d6', rarity: 'rare' },
  ],
  armor: [
    { name: 'Leather Armor', ac: 8, rarity: 'common' },
    { name: 'Studded Leather', ac: 7, rarity: 'common' },
    { name: 'Ring Mail', ac: 7, rarity: 'uncommon' },
    { name: 'Scale Mail', ac: 6, rarity: 'uncommon' },
    { name: 'Chain Mail', ac: 5, rarity: 'uncommon' },
    { name: 'Splint Mail', ac: 4, rarity: 'rare' },
    { name: 'Plate Mail', ac: 3, rarity: 'rare' },
  ],
  food: [{ name: 'Food Ration', nutrition: '900', rarity: 'common' }],
  lightSources: [
    { type: 'torch', name: 'Torch', radius: 2, fuel: 500, isPermanent: false, rarity: 'common' },
    {
      type: 'lantern',
      name: 'Lantern',
      radius: 2,
      fuel: 500,
      isPermanent: false,
      rarity: 'uncommon',
    },
    {
      type: 'artifact',
      name: 'Phial of Galadriel',
      radius: 3,
      isPermanent: true,
      rarity: 'legendary',
    },
  ],
  consumables: [{ name: 'Oil Flask', type: 'lantern_fuel', fuelAmount: 500, rarity: 'uncommon' }],
}
